{
  "version": "v1beta1",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "servicePath": "",
  "description": "Cloud Search provides cloud-based search capabilities over G Suite data.  The Cloud Search API allows indexing of non-G Suite data into Cloud Search.",
  "kind": "discovery#restDescription",
  "basePath": "",
  "id": "cloudsearch:v1beta1",
  "documentationLink": "https://gsuite.google.com/products/cloud-search/",
  "revision": "20180905",
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "Cloud Search",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.indexing"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.settings.indexing"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.settings"
        }
      }
    }
  },
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "cloudsearch",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Cloud Search API",
  "ownerName": "Google",
  "resources": {
    "settings": {
      "resources": {
        "datasources": {
          "methods": {
            "delete": {
              "id": "cloudsearch.settings.datasources.delete",
              "path": "v1beta1/settings/{+name}",
              "description": "Deletes a data source",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1beta1/settings/datasources/{datasourcesId}"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1beta1/settings/datasources/{datasourcesId}",
              "id": "cloudsearch.settings.datasources.get",
              "path": "v1beta1/settings/{+name}",
              "description": "Gets data source"
            },
            "list": {
              "description": "Lists data source",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1beta1/settings/datasources",
              "path": "v1beta1/settings/datasources",
              "id": "cloudsearch.settings.datasources.list"
            },
            "update": {
              "description": "Updates data source",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1beta1/settings/datasources/{datasourcesId}",
              "path": "v1beta1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.update"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1beta1/settings/datasources",
              "path": "v1beta1/settings/datasources",
              "id": "cloudsearch.settings.datasources.create",
              "description": "Data source\nCreate data source"
            }
          }
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "methods": {
            "getSchema": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1beta1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.getSchema",
              "description": "Gets the schema of a data source."
            },
            "updateSchema": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/schema",
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "path": "v1beta1/indexing/{+name}/schema",
              "description": "Updates the schema of a data source."
            },
            "deleteSchema": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1beta1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "description": "Deletes the schema of a data source."
            }
          },
          "resources": {
            "items": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "path": "v1beta1/indexing/{+name}",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "description": "Deletes Item resource for the\nspecified resource name."
                },
                "push": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/items/{itemsId}:push",
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "path": "v1beta1/indexing/{+name}:push",
                  "description": "Pushes an items onto a queue for later polling and updating."
                },
                "list": {
                  "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/items",
                  "path": "v1beta1/indexing/{+name}/items",
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "description": "Lists all or a subset of Item resources.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "upload": {
                  "path": "v1beta1/indexing/{+name}:upload",
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "description": "Creates an upload session for uploading item content. For items smaller\nthan 100 KiB, it's easier to embed the content\ninline within\nindex.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload"
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "path": "v1beta1/indexing/{+name}",
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "description": "Gets Item resource by item name."
                },
                "unreserve": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "path": "v1beta1/indexing/{+name}/items:unreserve",
                  "description": "Unreserves all items from a queue, making them all eligible to be\npolled.  This method is useful for resetting the indexing queue\nafter a connector has been restarted."
                },
                "index": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                  "path": "v1beta1/indexing/{+name}:index",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "description": "Updates Item ACL, metadata, and\ncontent. It will insert the Item if it\ndoes not exist.\nThis method does not support partial updates.  Fields with no provided\nvalues are cleared out in the Cloud Search index."
                },
                "poll": {
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "path": "v1beta1/indexing/{+name}/items:poll",
                  "description": "Polls for unreserved items from the indexing queue and marks a\nset as reserved, starting with items that have\nthe oldest timestamp from the highest priority\nItemStatus.\nThe priority order is as follows: \u003cbr /\u003e\nERROR\n\u003cbr /\u003e\nMODIFIED\n\u003cbr /\u003e\nNEW_ITEM\n\u003cbr /\u003e\nACCEPTED\n\u003cbr /\u003e\nReserving items ensures that polling from other threads\ncannot create overlapping sets.\n\nAfter handling the reserved items, the c[...]",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1beta1/indexing/datasources/{datasourcesId}/items:poll"
                }
              }
            }
          }
        }
      }
    },
    "query": {
      "methods": {
        "suggest": {
          "path": "v1beta1/query/suggest",
          "id": "cloudsearch.query.suggest",
          "description": "The Cloud Search Query API provides suggested text\nquery completions and people query suggestions.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "flatPath": "v1beta1/query/suggest"
        },
        "search": {
          "description": "The Cloud Search Query API provides the search method, which returns\nthe most relevant results from a user query.  The results can come from\nG Suite Apps, such as Gmail or Google Drive, or they can come from data\nthat you have indexed from a third party.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "flatPath": "v1beta1/query/search",
          "path": "v1beta1/query/search",
          "id": "cloudsearch.query.search"
        }
      }
    }
  }
}
